# Generated by Django 4.2.30 on 2026-05-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_delete_appointmentcancellation'),
        ('payments', '0003_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='stripe_checkout_id',
            field=models.CharField(max_length=255),
        ),
    ]
