# Generated by Django 4.2.30 on 2026-05-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_cancellation_failed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentCancellation',
        ),
    ]
